stages:
  - build
  - release

variables:
  BUILD_TYPE: Release
  RELEASE_DIR: release
  CCACHE_DIR: $CI_PROJECT_DIR/.ccache
  REGISTRY_IMAGE: "gitlab.bubki.zip:5050/d3156/dockerci"

.build_template: &build_template
  stage: build
  script:
    - mkdir -p Workspace/PluginsSource/$CI_PROJECT_NAME Workspace/Plugins 
    - mv * Workspace/PluginsSource/$CI_PROJECT_NAME/ || true
    - mkdir -p $CI_PROJECT_DIR/$RELEASE_DIR
    - cd Workspace
    - git clone https://gitlab.bubki.zip/d3156/PluginCore.git
    - ln -s ./PluginCore/tools tools
    - echo "Building for ARCH=$ARCH"
    - BUILD_DIR="build_$ARCH"
    - INSTALL_DIR=$(realpath ./core)
    - PLUGINS_DIR=$(realpath ./Plugins)
    - cd PluginsSource/$CI_PROJECT_NAME/
    - mkdir -p $INSTALL_DIR
    - |
      ASSETS=$(curl -L "https://gitlab.bubki.zip/api/v4/projects/d3156%2FPluginCore/releases/permalink/latest" | jq -r --arg ARCH "$ARCH" '.assets.links[] | select(.name | test("_"+$ARCH+"\\.deb$")) | .direct_asset_url')
      for url in $ASSETS; do
        echo "Downloading $url"
        curl -L -o "$INSTALL_DIR/$(basename $url)" "$url"
      done
    - ls -la $INSTALL_DIR/
    - chmod 777 $INSTALL_DIR/* || true
    - |
      for deb in "$INSTALL_DIR"/*.deb; do
        echo "Extracting $deb ..."
        dpkg-deb -x "$deb" $INSTALL_DIR
      done
    - tree .
    - ls -la $INSTALL_DIR/
    - |
      start_dir=$PWD
      find "$start_dir" -type f -name 'CMakeLists.txt' | while IFS= read -r cmake_file; do
        proj_dir=$(dirname "$cmake_file")
        echo "==== Release build: $proj_dir ===="
        (
          cd "$proj_dir" || exit 1
          cmake -S . -B $BUILD_DIR \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=$ARCH \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_PREFIX_PATH=$INSTALL_DIR/usr \
            $CMAKE_TOOLCHAIN_ARGS
          cmake --build $BUILD_DIR --verbose -j$(nproc)
        )
      done
    - ls -la $PLUGINS_DIR || true
    - |
      find $PLUGINS_DIR -type f | while IFS= read -r file_; do
        file_name=$(basename "$file_")
        mv "$file_" "$CI_PROJECT_DIR/$RELEASE_DIR/${file_name}_$ARCH"
      done
  before_script:
    - export PATH="/usr/lib/ccache:$PATH"
    - ccache -M 5G
  cache:
    key: global-build-cache
    paths:
      - .ccache/
      - build_amd64/
      - build_arm64/
      - build_armhf/
      - install_amd64/
      - install_arm64/
      - install_armhf/
  artifacts:
    paths:
      - $RELEASE_DIR/*
    expire_in: 1 week


# --- AMD64 ---
build:amd64:
  <<: *build_template
  image: $REGISTRY_IMAGE/ubuntu-builder-amd64:latest
  variables:
    ARCH: amd64
    CMAKE_TOOLCHAIN_ARGS: ""
  

# --- ARM64 ---
build:arm64:
  <<: *build_template
  image: $REGISTRY_IMAGE/ubuntu-builder-arm64:latest
  variables:
    ARCH: arm64
    CMAKE_TOOLCHAIN_ARGS: >
      -DCMAKE_SYSTEM_NAME=Linux
      -DCMAKE_SYSTEM_PROCESSOR=aarch64
      -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc-13
      -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++-13


# --- ARMhf / ARMv7 ---
build:armhf:
  <<: *build_template
  image: $REGISTRY_IMAGE/ubuntu-builder-armhf:latest
  variables:
    ARCH: armhf
    CMAKE_TOOLCHAIN_ARGS: >
      -DCMAKE_SYSTEM_NAME=Linux
      -DCMAKE_SYSTEM_PROCESSOR=arm
      -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc-12
      -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++-12

# --- GitLab Release ---
release:gitlab_release:
  stage: release
  image: $REGISTRY_IMAGE/ci-release:latest
  needs:
    - job: build:amd64
      artifacts: true
    - job: build:arm64
      artifacts: true
    - job: build:armhf
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - test -n "$GLAB_TOKEN" || (echo "GLAB_TOKEN is empty (check GitLab CI/CD variable scope/protected tags)" && exit 1)
    - tree .
    - echo "Release assets ready $(ls release/ | wc -l) files"
    - glab auth login --hostname gitlab.bubki.zip --token "$GLAB_TOKEN"
    - glab release create "$CI_COMMIT_TAG" --name "Multi-arch Release $CI_COMMIT_TAG" --notes "Release" || true
    - glab release upload "$CI_COMMIT_TAG" release/*
  artifacts:
    paths:
      - release/*
    expire_in: never


# --- GitHub Release ---
release:github_release:
  stage: release
  image: $REGISTRY_IMAGE/ci-release:latest
  needs:
    - job: build:amd64
      artifacts: true
    - job: build:arm64
      artifacts: true
    - job: build:armhf
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GITHUB_OWNER: d3156
  script:
    - ls -la release/
    - echo "Release assets ready $(ls release/ | wc -l) files"
    - test -n "$GH_TOKEN" || (echo "GH_TOKEN is empty (check GitLab CI/CD variable scope/protected tags)" && exit 1)
    - GH_REPO="$GITHUB_OWNER/$CI_PROJECT_NAME"
    - gh release create "$CI_COMMIT_TAG" release/* --repo "$GH_REPO" --title "Multi-arch Release $CI_COMMIT_TAG" --notes "New Release"
  artifacts:
    paths:
      - release/*
    expire_in: never
